"""create_gemes_table

Revision ID: 2
Revises: 1
Create Date: 2024-01-04 18:55:30.271082

"""
from typing import Sequence, Union
from src.constants import variables
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2'
down_revision: Union[str, None] = '1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'games',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('architecture', sa.String(), nullable=False),
        sa.Column('api', sa.String(), nullable=False),
        sa.Column('path', sa.String(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('path'),
        sa.CheckConstraint(f'architecture in {variables.ALL_ARCHITECTURES}', name='check_architecture'),
        sa.CheckConstraint(f'api in {variables.ALL_APIS}', name='check_api')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_architecture', 'games', type_='check')
    op.drop_constraint('check_api', 'games', type_='check')
    op.drop_table('games')
    # ### end Alembic commands ###
