#! /usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from src.constants import variables
from src.main_src import MainSrc
from src.resources import resources


class UiMain(object):
    def __init__(self):
        self.reshade_version_label = None
        self.main_tab_widget = None
        self.games_tab = None
        self.programs_table_widget = None
        self.selected_game_group_box = None
        self.edit_plugin_button = None
        self.reset_files_button = None
        self.edit_path_button = None
        self.open_game_path_button = None
        self.remove_button = None
        self.edit_game_button = None
        self.all_games_group_box = None
        self.apply_button = None
        self.add_button = None
        self.settings_tab = None
        self.check_program_updates_group_box = None
        self.yes_check_program_updates_radio_button = None
        self.no_check_program_updates_radio_button = None
        self.use_dark_theme_group_box = None
        self.yes_dark_theme_radio_button = None
        self.no_dark_theme_radio_button = None
        self.create_screenshots_folder_group_box = None
        self.yes_screenshots_folder_radio_button = None
        self.no_screenshots_folder_radio_button = None
        self.check_reshade_updates_group_box = None
        self.yes_check_reshade_updates_radio_button = None
        self.no_check_reshade_updates_radio_button = None
        self.no_show_info_messages_radio_button = None
        self.yes_show_info_messages_radio_button = None
        self.reset_all_button = None
        self.update_shaders_button = None
        self.edit_global_plugins_button = None
        self.about_tab = None
        self.update_avail_label = None
        self.update_button = None
        self.about_text_browser = None

    def setup_ui(self, main_form):
        main_form.setObjectName("main_form")
        main_form.resize(1000, 750)
        main_form.setMinimumSize(QtCore.QSize(1000, 750))
        main_form.setMaximumSize(QtCore.QSize(1000, 750))
        font = QtGui.QFont()
        font.setBold(False)
        main_form.setFont(font)
        self.reshade_version_label = QtWidgets.QLabel(parent=main_form)
        self.reshade_version_label.setGeometry(QtCore.QRect(860, 10, 120, 15))
        self.reshade_version_label.setMinimumSize(QtCore.QSize(120, 15))
        self.reshade_version_label.setMaximumSize(QtCore.QSize(120, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.reshade_version_label.setFont(font)
        self.reshade_version_label.setText("")
        self.reshade_version_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.reshade_version_label.setObjectName("reshade_version_label")
        self.main_tab_widget = QtWidgets.QTabWidget(parent=main_form)
        self.main_tab_widget.setGeometry(QtCore.QRect(20, 10, 960, 691))
        self.main_tab_widget.setMinimumSize(QtCore.QSize(960, 640))
        self.main_tab_widget.setIconSize(QtCore.QSize(20, 20))
        self.main_tab_widget.setUsesScrollButtons(False)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.games_tab = QtWidgets.QWidget()
        self.games_tab.setObjectName("games_tab")
        self.programs_table_widget = QtWidgets.QTableWidget(parent=self.games_tab)
        self.programs_table_widget.setGeometry(QtCore.QRect(0, 0, 960, 520))
        self.programs_table_widget.setMinimumSize(QtCore.QSize(960, 520))
        self.programs_table_widget.setMaximumSize(QtCore.QSize(960, 520))
        self.programs_table_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.programs_table_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.programs_table_widget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.programs_table_widget.setLineWidth(0)
        self.programs_table_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.programs_table_widget.setAutoScroll(False)
        self.programs_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.programs_table_widget.setDragDropOverwriteMode(False)
        self.programs_table_widget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.programs_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.programs_table_widget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.programs_table_widget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.programs_table_widget.setWordWrap(False)
        self.programs_table_widget.setCornerButtonEnabled(False)
        self.programs_table_widget.setColumnCount(5)
        self.programs_table_widget.setObjectName("programs_table_widget")
        self.programs_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.programs_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.programs_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.programs_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.programs_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.programs_table_widget.setHorizontalHeaderItem(4, item)
        self.programs_table_widget.horizontalHeader().setVisible(True)
        self.programs_table_widget.horizontalHeader().setDefaultSectionSize(120)
        self.programs_table_widget.horizontalHeader().setHighlightSections(False)
        self.programs_table_widget.horizontalHeader().setMinimumSectionSize(70)
        self.programs_table_widget.horizontalHeader().setSortIndicatorShown(False)
        self.programs_table_widget.verticalHeader().setVisible(True)
        self.programs_table_widget.verticalHeader().setDefaultSectionSize(30)
        self.programs_table_widget.verticalHeader().setMinimumSectionSize(30)
        self.selected_game_group_box = QtWidgets.QGroupBox(parent=self.games_tab)
        self.selected_game_group_box.setGeometry(QtCore.QRect(0, 530, 561, 120))
        self.selected_game_group_box.setObjectName("selected_game_group_box")
        self.edit_plugin_button = QtWidgets.QPushButton(parent=self.selected_game_group_box)
        self.edit_plugin_button.setGeometry(QtCore.QRect(200, 20, 160, 30))
        self.edit_plugin_button.setMinimumSize(QtCore.QSize(160, 30))
        self.edit_plugin_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.edit_plugin_button.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.edit_plugin_button.setIcon(icon)
        self.edit_plugin_button.setObjectName("edit_plugin_button")
        self.reset_files_button = QtWidgets.QPushButton(parent=self.selected_game_group_box)
        self.reset_files_button.setGeometry(QtCore.QRect(380, 20, 160, 30))
        self.reset_files_button.setMinimumSize(QtCore.QSize(160, 30))
        self.reset_files_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.reset_files_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/images/reset.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset_files_button.setIcon(icon1)
        self.reset_files_button.setObjectName("reset_files_button")
        self.edit_path_button = QtWidgets.QPushButton(parent=self.selected_game_group_box)
        self.edit_path_button.setGeometry(QtCore.QRect(19, 70, 160, 30))
        self.edit_path_button.setMinimumSize(QtCore.QSize(160, 30))
        self.edit_path_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.edit_path_button.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/images/arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.edit_path_button.setIcon(icon2)
        self.edit_path_button.setObjectName("edit_path_button")
        self.open_game_path_button = QtWidgets.QPushButton(parent=self.selected_game_group_box)
        self.open_game_path_button.setGeometry(QtCore.QRect(200, 70, 160, 30))
        self.open_game_path_button.setMinimumSize(QtCore.QSize(160, 30))
        self.open_game_path_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.open_game_path_button.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/images/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.open_game_path_button.setIcon(icon3)
        self.open_game_path_button.setObjectName("open_game_path_button")
        self.remove_button = QtWidgets.QPushButton(parent=self.selected_game_group_box)
        self.remove_button.setGeometry(QtCore.QRect(380, 70, 160, 30))
        self.remove_button.setMinimumSize(QtCore.QSize(160, 30))
        self.remove_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.remove_button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/images/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.remove_button.setIcon(icon4)
        self.remove_button.setObjectName("remove_button")
        self.edit_game_button = QtWidgets.QPushButton(parent=self.selected_game_group_box)
        self.edit_game_button.setGeometry(QtCore.QRect(20, 20, 160, 30))
        self.edit_game_button.setMinimumSize(QtCore.QSize(160, 30))
        self.edit_game_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.edit_game_button.setFont(font)
        self.edit_game_button.setIcon(icon)
        self.edit_game_button.setObjectName("edit_game_button")
        self.all_games_group_box = QtWidgets.QGroupBox(parent=self.games_tab)
        self.all_games_group_box.setGeometry(QtCore.QRect(579, 530, 371, 120))
        self.all_games_group_box.setObjectName("all_games_group_box")
        self.apply_button = QtWidgets.QPushButton(parent=self.all_games_group_box)
        self.apply_button.setGeometry(QtCore.QRect(200, 49, 160, 40))
        self.apply_button.setMinimumSize(QtCore.QSize(160, 40))
        self.apply_button.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.apply_button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/images/apply.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.apply_button.setIcon(icon5)
        self.apply_button.setObjectName("apply_button")
        self.add_button = QtWidgets.QPushButton(parent=self.all_games_group_box)
        self.add_button.setGeometry(QtCore.QRect(10, 49, 160, 40))
        self.add_button.setMinimumSize(QtCore.QSize(160, 40))
        self.add_button.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.add_button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/images/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_button.setIcon(icon6)
        self.add_button.setObjectName("add_button")
        self.selected_game_group_box.raise_()
        self.programs_table_widget.raise_()
        self.all_games_group_box.raise_()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/images/controller.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main_tab_widget.addTab(self.games_tab, icon7, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.check_program_updates_group_box = QtWidgets.QGroupBox(parent=self.settings_tab)
        self.check_program_updates_group_box.setGeometry(QtCore.QRect(100, 140, 330, 60))
        self.check_program_updates_group_box.setMinimumSize(QtCore.QSize(330, 60))
        self.check_program_updates_group_box.setMaximumSize(QtCore.QSize(330, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.check_program_updates_group_box.setFont(font)
        self.check_program_updates_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.check_program_updates_group_box.setObjectName("check_program_updates_group_box")
        self.yes_check_program_updates_radio_button = QtWidgets.QRadioButton(parent=self.check_program_updates_group_box)
        self.yes_check_program_updates_radio_button.setGeometry(QtCore.QRect(220, 30, 60, 20))
        self.yes_check_program_updates_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.yes_check_program_updates_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.yes_check_program_updates_radio_button.setObjectName("yes_check_program_updates_radio_button")
        self.no_check_program_updates_radio_button = QtWidgets.QRadioButton(parent=self.check_program_updates_group_box)
        self.no_check_program_updates_radio_button.setGeometry(QtCore.QRect(70, 30, 60, 20))
        self.no_check_program_updates_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.no_check_program_updates_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.no_check_program_updates_radio_button.setObjectName("no_check_program_updates_radio_button")
        self.use_dark_theme_group_box = QtWidgets.QGroupBox(parent=self.settings_tab)
        self.use_dark_theme_group_box.setGeometry(QtCore.QRect(500, 140, 330, 60))
        self.use_dark_theme_group_box.setMinimumSize(QtCore.QSize(330, 60))
        self.use_dark_theme_group_box.setMaximumSize(QtCore.QSize(330, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.use_dark_theme_group_box.setFont(font)
        self.use_dark_theme_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.use_dark_theme_group_box.setObjectName("use_dark_theme_group_box")
        self.yes_dark_theme_radio_button = QtWidgets.QRadioButton(parent=self.use_dark_theme_group_box)
        self.yes_dark_theme_radio_button.setGeometry(QtCore.QRect(220, 30, 60, 20))
        self.yes_dark_theme_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.yes_dark_theme_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.yes_dark_theme_radio_button.setObjectName("yes_dark_theme_radio_button")
        self.no_dark_theme_radio_button = QtWidgets.QRadioButton(parent=self.use_dark_theme_group_box)
        self.no_dark_theme_radio_button.setGeometry(QtCore.QRect(70, 30, 60, 20))
        self.no_dark_theme_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.no_dark_theme_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.no_dark_theme_radio_button.setObjectName("no_dark_theme_radio_button")
        self.create_screenshots_folder_group_box = QtWidgets.QGroupBox(parent=self.settings_tab)
        self.create_screenshots_folder_group_box.setGeometry(QtCore.QRect(100, 280, 330, 60))
        self.create_screenshots_folder_group_box.setMinimumSize(QtCore.QSize(330, 60))
        self.create_screenshots_folder_group_box.setMaximumSize(QtCore.QSize(330, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.create_screenshots_folder_group_box.setFont(font)
        self.create_screenshots_folder_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.create_screenshots_folder_group_box.setObjectName("create_screenshots_folder_group_box")
        self.yes_screenshots_folder_radio_button = QtWidgets.QRadioButton(parent=self.create_screenshots_folder_group_box)
        self.yes_screenshots_folder_radio_button.setGeometry(QtCore.QRect(220, 30, 60, 20))
        self.yes_screenshots_folder_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.yes_screenshots_folder_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.yes_screenshots_folder_radio_button.setObjectName("yes_screenshots_folder_radio_button")
        self.no_screenshots_folder_radio_button = QtWidgets.QRadioButton(parent=self.create_screenshots_folder_group_box)
        self.no_screenshots_folder_radio_button.setGeometry(QtCore.QRect(70, 30, 60, 20))
        self.no_screenshots_folder_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.no_screenshots_folder_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.no_screenshots_folder_radio_button.setObjectName("no_screenshots_folder_radio_button")
        self.check_reshade_updates_group_box = QtWidgets.QGroupBox(parent=self.settings_tab)
        self.check_reshade_updates_group_box.setGeometry(QtCore.QRect(100, 210, 330, 60))
        self.check_reshade_updates_group_box.setMinimumSize(QtCore.QSize(330, 60))
        self.check_reshade_updates_group_box.setMaximumSize(QtCore.QSize(330, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.check_reshade_updates_group_box.setFont(font)
        self.check_reshade_updates_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.check_reshade_updates_group_box.setObjectName("check_reshade_updates_group_box")
        self.yes_check_reshade_updates_radio_button = QtWidgets.QRadioButton(parent=self.check_reshade_updates_group_box)
        self.yes_check_reshade_updates_radio_button.setGeometry(QtCore.QRect(220, 30, 60, 20))
        self.yes_check_reshade_updates_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.yes_check_reshade_updates_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.yes_check_reshade_updates_radio_button.setObjectName("yes_check_reshade_updates_radio_button")
        self.no_check_reshade_updates_radio_button = QtWidgets.QRadioButton(parent=self.check_reshade_updates_group_box)
        self.no_check_reshade_updates_radio_button.setGeometry(QtCore.QRect(70, 30, 60, 20))
        self.no_check_reshade_updates_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.no_check_reshade_updates_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.no_check_reshade_updates_radio_button.setObjectName("no_check_reshade_updates_radio_button")
        self.show_info_messages_groupBox = QtWidgets.QGroupBox(parent=self.settings_tab)
        self.show_info_messages_groupBox.setGeometry(QtCore.QRect(500, 210, 330, 60))
        self.show_info_messages_groupBox.setMinimumSize(QtCore.QSize(330, 60))
        self.show_info_messages_groupBox.setMaximumSize(QtCore.QSize(330, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.show_info_messages_groupBox.setFont(font)
        self.show_info_messages_groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.show_info_messages_groupBox.setObjectName("show_info_messages_groupBox")
        self.no_show_info_messages_radio_button = QtWidgets.QRadioButton(parent=self.show_info_messages_groupBox)
        self.no_show_info_messages_radio_button.setGeometry(QtCore.QRect(70, 30, 60, 20))
        self.no_show_info_messages_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.no_show_info_messages_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.no_show_info_messages_radio_button.setObjectName("no_show_info_messages_radio_button")
        self.yes_show_info_messages_radio_button = QtWidgets.QRadioButton(parent=self.show_info_messages_groupBox)
        self.yes_show_info_messages_radio_button.setGeometry(QtCore.QRect(220, 30, 60, 20))
        self.yes_show_info_messages_radio_button.setMinimumSize(QtCore.QSize(60, 20))
        self.yes_show_info_messages_radio_button.setMaximumSize(QtCore.QSize(60, 20))
        self.yes_show_info_messages_radio_button.setObjectName("yes_show_info_messages_radio_button")
        self.reset_all_button = QtWidgets.QPushButton(parent=self.settings_tab)
        self.reset_all_button.setGeometry(QtCore.QRect(500, 370, 335, 30))
        self.reset_all_button.setMinimumSize(QtCore.QSize(335, 30))
        self.reset_all_button.setMaximumSize(QtCore.QSize(335, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.reset_all_button.setFont(font)
        self.reset_all_button.setIcon(icon1)
        self.reset_all_button.setIconSize(QtCore.QSize(27, 27))
        self.reset_all_button.setObjectName("reset_all_button")
        self.update_shaders_button = QtWidgets.QPushButton(parent=self.settings_tab)
        self.update_shaders_button.setGeometry(QtCore.QRect(500, 290, 335, 30))
        self.update_shaders_button.setMaximumSize(QtCore.QSize(335, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.update_shaders_button.setFont(font)
        self.update_shaders_button.setIcon(icon1)
        self.update_shaders_button.setIconSize(QtCore.QSize(27, 27))
        self.update_shaders_button.setObjectName("update_shaders_button")
        self.edit_global_plugins_button = QtWidgets.QPushButton(parent=self.settings_tab)
        self.edit_global_plugins_button.setGeometry(QtCore.QRect(500, 330, 335, 30))
        self.edit_global_plugins_button.setMaximumSize(QtCore.QSize(335, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.edit_global_plugins_button.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resources/images/plugin.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.edit_global_plugins_button.setIcon(icon8)
        self.edit_global_plugins_button.setIconSize(QtCore.QSize(27, 27))
        self.edit_global_plugins_button.setObjectName("edit_global_plugins_button")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resources/images/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main_tab_widget.addTab(self.settings_tab, icon9, "")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.about_text_browser = QtWidgets.QTextBrowser(parent=self.about_tab)
        self.about_text_browser.setGeometry(QtCore.QRect(0, 0, 960, 610))
        self.about_text_browser.setMinimumSize(QtCore.QSize(960, 610))
        self.about_text_browser.setMaximumSize(QtCore.QSize(960, 610))
        self.about_text_browser.setAcceptDrops(False)
        self.about_text_browser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.about_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.about_text_browser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.about_text_browser.setUndoRedoEnabled(False)
        self.about_text_browser.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.about_text_browser.setOpenExternalLinks(True)
        self.about_text_browser.setObjectName("about_text_browser")
        self.donate_button = QtWidgets.QPushButton(parent=self.about_tab)
        self.donate_button.setGeometry(QtCore.QRect(360, 20, 230, 90))
        self.donate_button.setMinimumSize(QtCore.QSize(230, 90))
        self.donate_button.setMaximumSize(QtCore.QSize(230, 90))
        self.donate_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.donate_button.setToolTip("Donate")
        self.donate_button.setAutoFillBackground(False)
        self.donate_button.setStyleSheet("#donate_button {\n"
"    background-color: transparent;\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}")
        self.donate_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/resources/images/donate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.donate_button.setIcon(icon10)
        self.donate_button.setIconSize(QtCore.QSize(150, 100))
        self.donate_button.setObjectName("donate_button")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/resources/images/help.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.main_tab_widget.addTab(self.about_tab, icon11, "")
        self.update_avail_label = QtWidgets.QLabel(parent=main_form)
        self.update_avail_label.setGeometry(QtCore.QRect(300, 705, 480, 40))
        self.update_avail_label.setMinimumSize(QtCore.QSize(480, 40))
        self.update_avail_label.setMaximumSize(QtCore.QSize(480, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.update_avail_label.setFont(font)
        self.update_avail_label.setText("")
        self.update_avail_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.update_avail_label.setObjectName("update_avail_label")
        self.update_button = QtWidgets.QPushButton(parent=main_form)
        self.update_button.setGeometry(QtCore.QRect(800, 710, 160, 30))
        self.update_button.setMinimumSize(QtCore.QSize(160, 30))
        self.update_button.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.update_button.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/resources/images/update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.update_button.setIcon(icon12)
        self.update_button.setObjectName("update_button")
        self.main_tab_widget.raise_()
        self.update_avail_label.raise_()
        self.update_button.raise_()
        self.reshade_version_label.raise_()

        self.retranslate_ui(main_form)
        self.main_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_form)
        main_form.setTabOrder(self.main_tab_widget, self.update_button)
        main_form.setTabOrder(self.update_button, self.programs_table_widget)
        main_form.setTabOrder(self.programs_table_widget, self.no_screenshots_folder_radio_button)
        main_form.setTabOrder(self.no_screenshots_folder_radio_button, self.yes_screenshots_folder_radio_button)
        main_form.setTabOrder(self.yes_screenshots_folder_radio_button, self.no_check_reshade_updates_radio_button)
        main_form.setTabOrder(self.no_check_reshade_updates_radio_button, self.yes_check_reshade_updates_radio_button)
        main_form.setTabOrder(self.yes_check_reshade_updates_radio_button, self.no_dark_theme_radio_button)
        main_form.setTabOrder(self.no_dark_theme_radio_button, self.yes_dark_theme_radio_button)
        main_form.setTabOrder(self.yes_dark_theme_radio_button, self.no_show_info_messages_radio_button)
        main_form.setTabOrder(self.no_show_info_messages_radio_button, self.yes_show_info_messages_radio_button)
        main_form.setTabOrder(self.yes_show_info_messages_radio_button, self.no_check_program_updates_radio_button)
        main_form.setTabOrder(self.no_check_program_updates_radio_button, self.yes_check_program_updates_radio_button)
        main_form.setTabOrder(self.yes_check_program_updates_radio_button, self.reset_all_button)
        main_form.setTabOrder(self.reset_all_button, self.donate_button)
        main_form.setTabOrder(self.donate_button, self.about_text_browser)

        main_src = MainSrc(self, main_form)
        main_src.start()

    def retranslate_ui(self, main_form):
        _translate = QtCore.QCoreApplication.translate
        main_form.setWindowTitle(_translate("main_form", variables.FULL_PROGRAM_NAME))
        item = self.programs_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("main_form", "NAME"))
        item = self.programs_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("main_form", "ARCHITECTURE"))
        item = self.programs_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("main_form", "API"))
        item = self.programs_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("main_form", "DLL"))
        item = self.programs_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("main_form", "FILE"))
        self.selected_game_group_box.setTitle(_translate("main_form", "Selected Game"))
        self.edit_plugin_button.setToolTip(_translate("main_form", "Edit the selected reshade preset file"))
        self.edit_plugin_button.setText(_translate("main_form", "EDIT PLUGIN"))
        self.reset_files_button.setToolTip(_translate("main_form", "Reset all the selected game files"))
        self.reset_files_button.setText(_translate("main_form", "RESET FILES"))
        self.edit_path_button.setToolTip(_translate("main_form", "Edit the selected game path"))
        self.edit_path_button.setText(_translate("main_form", "CHANGE LOCATION"))
        self.open_game_path_button.setToolTip(_translate("main_form", "Open the selected game location in explorer"))
        self.open_game_path_button.setText(_translate("main_form", "OPEN LOCATION"))
        self.remove_button.setToolTip(_translate("main_form", "Delete the selected game"))
        self.remove_button.setText(_translate("main_form", "REMOVE"))
        self.edit_game_button.setToolTip(_translate("main_form", "Edit the selected game name"))
        self.edit_game_button.setText(_translate("main_form", "EDIT NAME"))
        self.all_games_group_box.setTitle(_translate("main_form", "All Games"))
        self.apply_button.setToolTip(_translate("main_form", "Apply Reshade to All Games"))
        self.apply_button.setText(_translate("main_form", "APPLY"))
        self.add_button.setToolTip(_translate("main_form", "Add a game"))
        self.add_button.setText(_translate("main_form", "ADD"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.games_tab), _translate("main_form", "GAMES"))
        self.check_program_updates_group_box.setTitle(_translate("main_form", "Check for Program Updates on Startup"))
        self.yes_check_program_updates_radio_button.setText(_translate("main_form", "YES"))
        self.no_check_program_updates_radio_button.setText(_translate("main_form", "NO"))
        self.use_dark_theme_group_box.setTitle(_translate("main_form", "Dark Theme"))
        self.yes_dark_theme_radio_button.setText(_translate("main_form", "YES"))
        self.no_dark_theme_radio_button.setText(_translate("main_form", "NO"))
        self.create_screenshots_folder_group_box.setTitle(_translate("main_form", "Create Game Screenshot Folder"))
        self.yes_screenshots_folder_radio_button.setText(_translate("main_form", "YES"))
        self.no_screenshots_folder_radio_button.setText(_translate("main_form", "NO"))
        self.check_reshade_updates_group_box.setTitle(_translate("main_form", "Check for Reshade Updates on Startup"))
        self.yes_check_reshade_updates_radio_button.setText(_translate("main_form", "YES"))
        self.no_check_reshade_updates_radio_button.setText(_translate("main_form", "NO"))
        self.show_info_messages_groupBox.setTitle(_translate("main_form", "Show Confirmation Messages"))
        self.no_show_info_messages_radio_button.setText(_translate("main_form", "NO"))
        self.yes_show_info_messages_radio_button.setText(_translate("main_form", "YES"))
        self.reset_all_button.setToolTip(_translate("main_form", "Reset all games files to default"))
        self.reset_all_button.setText(_translate("main_form", "RESET ALL GAMES FILES TO DEFAULT"))
        self.update_shaders_button.setToolTip(_translate("main_form", "Update shaders"))
        self.update_shaders_button.setText(_translate("main_form", "UPDATE SHADERS"))
        self.edit_global_plugins_button.setToolTip(_translate("main_form", "Edit global plugins"))
        self.edit_global_plugins_button.setText(_translate("main_form", "EDIT GLOBAL PLUGINS"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.settings_tab), _translate("main_form", "SETTINGS"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.about_tab), _translate("main_form", "ABOUT"))
        self.update_button.setToolTip(_translate("main_form", "Update ReshadeUtils"))
        self.update_button.setText(_translate("main_form", "UPDATE"))
        with open("src/ui/about.html", "r") as about_file:
            self.about_text_browser.setHtml(_translate("main_form", about_file.read()))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mf = QtWidgets.QWidget()
    ui = UiMain()
    ui.setup_ui(mf)
    mf.show()
    sys.exit(app.exec())
