[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ReShadeUtils"
version = "5.0.0"
description = "ReShadeUtils"
authors = ["ddc <danieldcsta@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
beautifulsoup4 = "^4.12.3"
urllib3 = "^2.2.1"
SQLAlchemy = "^2.0.25"
requests = "^2.31.0"
PyQt6 = "^6.6.1"
alembic = "^1.13.1"
ddcutils = "^1.0.23"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.1"
faker = "^23.2.1"
coverage = "^7.4.0"
pytest-qt = "^4.3.1"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.3.0"


[tool.poe.tasks]
test = "poetry run coverage run -m pytest -v"
coverage = "poetry run coverage report"
