[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ReShadeUtils"
version = "5.0.1"
description = "ReShadeUtils"
authors = ["ddc <danieldcsta@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
bs4 = "^0.0.2"
urllib3 = "^2.2.1"
SQLAlchemy = "^2.0.28"
requests = "^2.31.0"
PyQt6 = "^6.6.1"
alembic = "^1.13.1"
ddcutils = "^1.0.23"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
faker = "^24.3.0"
coverage = "^7.4.4"
pytest-qt = "^4.4.0"
poethepoet = "^0.25.0"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.5.0"

[tool.poe.tasks]
test = "poetry run coverage run -m pytest -v"
tests = ["test"]
coverage = "poetry run coverage report"
