[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ReShadeUtils"
version = "5.0.2"
description = "ReShadeUtils"
authors = ["ddc <danieldcsta@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
bs4 = "^0.0.2"
urllib3 = "^2.2.1"
SQLAlchemy = "^2.0.29"
requests = "^2.31.0"
PyQt6 = "^6.7.0"
alembic = "^1.13.1"
ddcutils = "^1.0.24"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"
faker = "^25.0.0"
coverage = "^7.5.0"
pytest-qt = "^4.4.0"
poethepoet = "^0.26.1"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.6.0"

[tool.poe.tasks]
test = "poetry run coverage run -m pytest -v"
tests = ["test"]
coverage = "poetry run coverage report"
