name: Run Tests

on:
  push:
    branches:
      - "**"

jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libegl1

      - name: Install poetry
        run: |  
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install poetry

      - name: Install poetry dependencies
        run: |  
          python -m poetry update --with test

      - name: Run tests
        run: |  
          python -m poetry run coverage run --omit=tests/*,src/events/*,src/tools/qt/*,src/edit_form.py --m pytest -v

      - name: Generate Coverage Report
        run: |  
          python -m poetry run coverage report
          python -m poetry run coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: ddc/ReShadeUtils
